name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Print Version
        run: echo ${GITHUB_REF/refs\/tags\//}
      - name: Publish package
        run: gradle publish
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          VERSION: ${GITHUB_REF/refs\/tags\//}