name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Run JDK configuration
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      #Gradle cache configuration
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      #Authorizing gradlew files
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #Build project
      - name: Build with Gradle
        run: ./gradlew build

      #After decoding the secret key, place the file in ~ /. Gradle/ secring.gpg
      - name: Decode
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      # Get version
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      #Publish project
      - name: Publish
        run: ./gradlew publish -PVERSION_NAME=${{ steps.get_version.outputs.VERSION }} -PossrhUsername=${{ secrets.OSSRH_USERNAME }} -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password=${{ secrets.SIGNING_KEY_PASSWORD }} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)